# Generated by Django 4.2.23 on 2025-07-04 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField(help_text="Incrementing; start at 1")),
                (
                    "code",
                    models.TextField(
                        help_text="Full Python script, runnable out-of-the-box"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Only one version per eval is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_code_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="Eval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Relevance & Fluency Test'", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvalRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "run_params",
                    models.JSONField(
                        default=dict, help_text="Overrides or flags for this run"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="api.codeversion",
                    ),
                ),
                (
                    "eval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="api.eval",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="EvalSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'June 2025 translation prompts'", max_length=255
                    ),
                ),
                (
                    "file_url",
                    models.URLField(help_text="Azure Blob SAS URL", max_length=500),
                ),
                (
                    "row_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional; for quick sanity checks",
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eval_sets",
                        to="api.eval",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_eval_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EvalSetItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(help_text="Original CSV line number"),
                ),
                (
                    "input_payload",
                    models.JSONField(help_text="The parsed prompt/fields row"),
                ),
                (
                    "reference_output",
                    models.JSONField(
                        blank=True, help_text="Optional 'ground truth'", null=True
                    ),
                ),
                (
                    "eval_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.evalset",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
                "unique_together": {("eval_set", "row_number")},
            },
        ),
        migrations.CreateModel(
            name="RunResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_output",
                    models.TextField(help_text="Raw response from the endpoint"),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict, help_text="BLEU/ROUGE/etc. computed metrics"
                    ),
                ),
                (
                    "scores",
                    models.JSONField(
                        default=dict, help_text="User or AI-generated rubric scores"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eval_set_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL if you skip items table",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="api.evalsetitem",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="api.evalrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Chatbot Quality Audit'", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="eval",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evals",
                to="api.project",
            ),
        ),
        migrations.CreateModel(
            name="EndpointIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'OpenAI GPT-4 Turbo'", max_length=255
                    ),
                ),
                ("endpoint_url", models.URLField(max_length=500)),
                (
                    "http_method",
                    models.CharField(
                        choices=[("POST", "POST"), ("GET", "GET")],
                        default="POST",
                        max_length=10,
                    ),
                ),
                (
                    "param_schema",
                    models.JSONField(
                        help_text="Schema for parameters, e.g. {'prompt': 'string', 'temperature': 'number'}"
                    ),
                ),
                (
                    "param_defaults",
                    models.JSONField(
                        default=dict,
                        help_text="User-provided defaults for missing params",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoint_integrations",
                        to="api.eval",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="codeversion",
            name="eval",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_versions",
                to="api.eval",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codeversion",
            unique_together={("eval", "version")},
        ),
    ]
