# Generated by Django 4.2.23 on 2025-07-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evalset",
            name="endpoint_integration",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional; can be assigned later",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eval_sets",
                to="api.endpointintegration",
            ),
        ),
        migrations.AlterField(
            model_name="endpointintegration",
            name="http_method",
            field=models.CharField(
                choices=[
                    ("POST", "POST"),
                    ("GET", "GET"),
                    ("PUT", "PUT"),
                    ("PATCH", "PATCH"),
                ],
                default="POST",
                max_length=10,
            ),
        ),
    ]
