# Generated by Django 4.2.23 on 2025-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_evalset_endpoint_integration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpointintegration",
            name="test_examples",
            field=models.JSONField(
                default=list,
                help_text="Up to 3 test examples for LLM to understand the API schema",
            ),
        ),
    ]
