# Generated by Django 4.2.23 on 2025-07-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_endpointintegration_test_examples"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeversion",
            name="endpoint_integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_versions",
                to="api.endpointintegration",
            ),
        ),
        migrations.AddField(
            model_name="codeversion",
            name="eval_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_versions",
                to="api.evalset",
            ),
        ),
    ]
